### ISSUE TITLE
Too slow.

### ISSUE THREAD

**Issue by thyrgle** [GamesCrafters/GamesmanMPI#38]
Takes about 20 seconds on my machine to complete 10-1. Seems too slow. Might be the way we are performing communication, might be some other issue.

**Comment by swerwath** [comment]
Mine finishes 10-1 in less than a second, and 25-1 in 2.3 seconds after I removed the time delay in run() and the logging statements. FileIO for logging may be slowing you down.

**Comment by thyrgle** [comment]
Forgot about that. Thanks. Definitely seems to speed things up.

**Comment by thyrgle** [comment]
Also, for anyone wondering...

```
mpiexec -n 5 python -O solver_launcher.py four_to_one.py
```

The `-O` flag removes the debug statements.
