### ISSUE TITLE
TicTacToe reduction problems.

### ISSUE THREAD

**Issue by thyrgle** [GamesCrafters/GamesmanMPI#39]
I'm not going to push up the TicTacToe code as Stevie plans to but the code for TicTacToe in the GamesmanSpark repo fails at reduction. This may be an issue with my slight tweaking of the TicTacToe code, but I doubt it:

```
    if res1.state == LOSS and res2.state == LOSS:
AttributeError: 'str' object has no attribute 'state'
```

**Comment by swerwath** [comment]
This is the issue that we thought should have been occurring with 4-1 but wasn't... should be a simple fix I can do.

**Comment by thyrgle** [comment]
Fixed the syntactical errors for remoteness, but I believe TicTacToe still takes too long to solve. I could leave it running for a while and see if it completes though. I am not actually sure how long it should take a naive solver to solve. Should probably investigate that for a baseline.

**Comment by thyrgle** [comment]
Actually, I think I will close this and open another issue related to solving TicTacToe quickly.
