### ISSUE TITLE
Solving TicTacToe.

### ISSUE THREAD

**Issue by thyrgle** [GamesCrafters/GamesmanMPI#41]
TicTacToe (modified mttt.py from the GamesmanSpark repo) takes forever. I don't think it should. Possibly a bug somewhere?

**Comment by swerwath** [comment]
On my system, the local solver takes 1 minute 20 seconds, while the distributed solver takes 2 minutes. Keep in mind, the distributed solver also takes care of remoteness, while the local solver does not.

**Comment by thyrgle** [comment]
How many processes did you use? If you used 1 process this isn't actually too unreasonable, but if it is 8 I would suspect a performance boost instead of a performance decrease.

**Comment by thyrgle** [comment]
Ok. Tested on 4 processes... Doesn't seem too bad given that we have some overhead from mpi4py and we might be pickling a lot of objects because of the way we set stuff up.
