### ISSUE TITLE
Solver reshapes numpy arrays

### ISSUE THREAD

**Issue by areardon11** [GamesCrafters/GamesmanMPI#71]

**Comment by areardon11** [comment]
The solver reshapes numpy arrays to be one dimensional instead of two dimensional.  For example, try adding " print state " as the first line in gen moves for tic tac toe.  It is a one dimensional array of 9 entries instead of a 3 by 3 two dimensional array.  

Even if this can't be fixed from the solver side, I believe it can be fixed from the game implementation side pretty easily by reshaping the state array.  Hopefully.

**Comment by swerwath** [comment]
I think I know the issue, will fix tonight

**Comment by thyrgle** [comment]
I believe this is fixed in #73
